Repository palantir/conjure, pull requests merged in 2019-10, with the labels that each got.

#408 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#367 Add 401 Unauthenticated to conjure error types
  conjure-api/src/main/conjure/conjure-api.yml
  docs/spec/conjure_definitions.md
  docs/spec/wire.md
Labels: merge when ready, no changelog

#422 Fix: Don't allow a union variant called 'type'
  changelog/@unreleased/pr-422.v2.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/validator/UnionDefinitionValidator.java
Labels: merge when ready

#423 Fix #325: Validate map keys have PLAIN representation
  changelog/@unreleased/pr-423.v2.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
  conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java
Labels: autorelease, merge when ready

#426 Revert "Add 401 Unauthenticated to conjure error types"
  changelog/@unreleased/pr-422.v2.yml
  changelog/@unreleased/pr-423.v2.yml
  conjure-api/src/main/conjure/conjure-api.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/validator/ConjureDefinitionValidator.java
  docs/spec/conjure_definitions.md
  docs/spec/wire.md
Labels: autorelease, merge when ready
