Repository palantir/conjure, pull requests merged in 2020-02, with the labels that each got.

#497 Fix #491: Validate against binary data in non-body container parameters
  changelog/@unreleased/pr-497.v2.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
  conjure-core/src/test/java/com/palantir/conjure/defs/validator/EndpointDefinitionTest.java
  conjure-core/src/test/resources/spec-tests/services.yml
Labels: merge when ready

#494 Fix #120: Enum values, fields, and union values support deprecation
  changelog/@unreleased/pr-494.v2.yml
  conjure-api/src/main/conjure/conjure-api.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
  conjure-core/src/main/java/com/palantir/conjure/parser/types/complex/EnumValueDefinition.java
  conjure-core/src/main/java/com/palantir/conjure/parser/types/complex/FieldDefinition.java
  conjure-core/src/test/java/com/palantir/conjure/defs/validator/ConjureSourceFileValidatorTest.java
  conjure-core/src/test/java/com/palantir/conjure/parser/ConjureParserTest.java
  conjure-core/src/test/java/com/palantir/conjure/validator/FieldDefinitionValidatorTest.java
  conjure-core/src/test/resources/example-deprecation.yml
  conjure-core/src/test/resources/normalized.conjure.json
  docs/spec/conjure_definitions.md
  docs/spec/intermediate_representation.md
Labels: autorelease, merge when ready

#498 Fix deprecated docs
  docs/spec/conjure_definitions.md
Labels: merge when ready, no changelog

#533 Conjure CLI is permissive with unknown options
  changelog/@unreleased/pr-533.v2.yml
  conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java
  conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java
Labels: autorelease, merge when ready

#532 add extensions to conjure
  changelog/@unreleased/pr-532.v2.yml
  conjure-api/src/main/conjure/conjure-api.yml
  conjure-core/src/test/resources/normalized.conjure.json
  conjure/src/main/java/com/palantir/conjure/cli/CliConfiguration.java
  conjure/src/main/java/com/palantir/conjure/cli/ConjureCli.java
  conjure/src/test/java/com/palantir/conjure/cli/ConjureCliTest.java
  docs/spec/intermediate_representation.md
Labels: autorelease, merge when ready

#537 Better error message telling you which file the error came from
  changelog/@unreleased/pr-537.v2.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/Conjure.java
  conjure-core/src/main/java/com/palantir/conjure/defs/ConjureParserUtils.java
  conjure-core/src/main/java/com/palantir/conjure/parser/AnnotatedConjureSourceFile.java
  conjure-core/src/main/java/com/palantir/conjure/parser/ConjureParser.java
  conjure-core/src/test/java/com/palantir/conjure/defs/ConjureDefTest.java
  conjure-core/src/test/java/com/palantir/conjure/defs/ConjureSpecTest.java
Labels: autorelease, merge when ready
