Repository palantir/conjure, pull requests merged in 2021-04, with the labels that each got.

#834 fix changelog format
  changelog/@unreleased/pr-814.v2.yml
Labels: autorelease, merge when ready, no changelog

#835 Validate conjure headers do not set protocol headers.
  changelog/@unreleased/pr-835.v2.yml
  conjure-core/src/main/java/com/palantir/conjure/defs/validator/EndpointDefinitionValidator.java
  conjure-core/src/test/java/com/palantir/conjure/defs/validator/ParamIdValidatorTest.java
Labels: autorelease, merge when ready

#848 Fix broken liche checks
  .circleci/config.yml
  CONTRIBUTING.md
  changelog/@unreleased/pr-848.v2.yml
Labels: merge when ready
